version: "2"

services:
  redis:
    image: redis:latest

  pj_chat_db:
    image: mysql
    ports:
        - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: chatStreamBoard
        MYSQL_USER: user
        MYSQL_PASSWORD: chatStreamBoard
        MYSQL_DATABASE: pj_chat_ms_development
        MYSQL_HOST: pj_chat_db

  pj_chat_ms:
    build: .
    command: bash -c "python3.6 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - pj_chat_db
