version: "2"
services:
  chat-db-1:
    image: redis:latest

  chat-db:
    image: mysql
    ports:
        - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: chatStreamBoard
        MYSQL_USER: user
        MYSQL_PASSWORD: chatStreamBoard
        MYSQL_DATABASE: chat_ms_development
        MYSQL_HOST: chat-db

  chat-ms:
    build: .
    command: bash -c "python3.6 manage.py runserver 0.0.0.0:8000"
    ports:
      - "4004:8000"
    depends_on:
      - chat-db-1
      - chat-db
