# Generated by Django 2.0.2 on 2018-04-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_chat_ms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_id',
            field=models.PositiveIntegerField(default=1, verbose_name='user id'),
            preserve_default=False,
        ),
    ]
